### ISSUE TITLE
Project dir changes between jobs which breaks some tools.

### ISSUE THREAD

**Issue by matclab** [firecow/gitlab-ci-local#440] opened 2022-04-28 13:33 UTC
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
image:
  name: bash

import:
  script: # import project under eclispe generate a workspace
    - set -eo pipefail
    - echo $CI_PROJECT_DIR
    - mkdir -p workspace && echo "$(pwd)/project" > workspace/config
  artifacts:
    paths:
      - workspace

gen:
  needs:
    - import
  dependencies:
    - import
  script:
    - set -eo pipefail
    - echo $CI_PROJECT_DIR
    - cd $(cat workspace/config)

```

**Expected behavior**
Should pass : https://gitlab.com/matclab/gitlab-ci-local-test/-/pipelines/527043993
Whereas it gives: 
```
parsing and downloads finished in 32 ms
import starting bash:latest (test)
import pulled bash:latest in 57 ms
import copied to container in 59 ms
import $ set -eo pipefail
import $ echo $CI_PROJECT_DIR
import > /builds/import
import $ mkdir -p workspace && echo "$(pwd)/project" > workspace/config
import exported artifacts in 755 ms
import copied artifacts to cwd in 55 ms
import finished in 1.97 s
gen    starting bash:latest (test)
gen    pulled bash:latest in 112 ms
gen    copied to container in 93 ms
gen    imported artifacts in 90 ms
gen    $ set -eo pipefail
gen    $ echo $CI_PROJECT_DIR
gen    > /builds/gen
gen    $ cd $(cat workspace/config)
gen    > /gcl-scripts/gen: line 8: cd: /builds/import/project: No such file or directory
gen    finished in 1.51 s  FAIL 1  

 PASS  import
 FAIL  gen   
  > /builds/gen
  > /gcl-scripts/gen: line 8: cd: /builds/import/project: No such file or directory
```

**Host information**
Arch linux 
gitlab-ci-local 4.30.1.r16.g000a3ef (from git)

**Additional context**
When using a docker runner, the projetc path is not consistent between each jobs and thus the artifacts paths may change between jobs.
Some tools (like eclipse) use absolute paths when configured (for exemple when importing existing eclipse projects) and as such they need to have a stable project paths between jobs.

**Comment by firecow** [comment] 2022-04-28 14:34
On remote the project paths doesn't have stable absolute paths either, unless you are just lucky. Perhaps you are running jobs only in sequence.

**Comment by firecow** [comment] 2022-04-28 14:38
On remote the project paths doesn't have stable absolute paths either, unless you are just lucky. Perhaps you are running jobs only in sequence.
Ahh, hang on. I'll try and reproduce.
I might be mistaken...

**Comment by vinman1** [comment] 2022-06-17 02:07
I've run into this issue because i'm caching dependencies between jobs and the paths where the dependencies were originally resolved no longer matches the path where they are restored from the cache.

e.g. Dependencies get pulled and stored here:
```script
/builds/flutter_pub_get/.pub-cache/...
```
But they are restored from the cache here:
```script
/builds/flutter_analyze/.pub-cache/...
```

While the relative path to the dependencies from the repo root might be the same, there are files in the repo that reference those dependencies via their absolute path, and therefore can't find them once restored from the cache.

**Comment by vinman1** [comment] 2022-06-17 02:24
FYI, I tried explicitly setting the $CI_PROJECT_DIR variable to force it to the same value for all jobs but that doesn't help because the jobs don't actually run from the directory specified in that variable.

**Comment by firecow** [comment] 2022-06-17 05:50
@vinman1 Can you provide an as small as possible `.gitlab-ci.yml` i can use for debugging/testing purposes?

**Comment by matclab** [comment] 2022-06-17 06:08
> @vinman1 Can you provide an as small as possible `.gitlab-ci.yml` i can use for debugging/testing purposes?

Didn't the one given in the initial report allow you to reproduce the problem ? (Or perhaps you are speaking about another problem)...

**Comment by firecow** [comment] 2022-06-17 06:43
@matclab The initial one doesn't include cache

**Comment by firecow** [comment] 2022-06-17 06:46
@matclab The initial one doesn't include cache.
Edit: But I just read his comment a little better and the solution is the same.

**Comment by vinman1** [comment] 2022-06-20 00:19
@firecow, as a suggestion, wouldn't a sensible solution be to use the project's name (equivalent to `${CI_PROJECT_NAME}`) instead of the job name (`${CI_JOB_NAME}`)? 

So if my project's full URL was: `gitlab.example.com/group-name/project-1`, then ALL CI jobs for that project would execute in the folder:

```shell
/builds/project-1
```

for both docker & shell executors.

**Comment by firecow** [comment] 2022-06-20 04:28
For shell executor that would be "wrong"...
Since their absolute path change on each run, or at least can change on each run.

**Comment by vinman1** [comment] 2022-06-20 19:56
While I don't understand why the path could change for each run, I understand that it might be challenging to stop supporting that behavior...

Could we in a first iteration, fix this issue for the docker executor? This would (I think) address both my and @matclab's issue, and would allow us to reflect on the best way to address the shell executor...

**Comment by firecow** [comment] 2022-06-20 19:57
I'm just saying shell-executor use different paths.
docker-executor paths will be fixed.

**Closed** 2022-06-22 19:33 UTC
Labels: bug

**Comment by matclab** [comment] 2022-06-23 05:59
Thank you very much @firecow !
