### ISSUE TITLE
Source files missing from service container

### ISSUE THREAD

**Issue by haydenseitz** [firecow/gitlab-ci-local#616] opened 2022-10-12 01:18 UTC
**Is your feature request related to a problem? Please describe.**
According to [the docs](https://docs.gitlab.com/ee/ci/services/#how-docker-integration-works), GitLab runners mount the $CI_PROJECT_DIR (`/builds/group-name/project-name/`) to both _job_ containers and _service_ containers. This allows docker-in-docker jobs like [browser_performance](https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Verify/Browser-Performance.gitlab-ci.yml) to share files between the job container and the dind service container. It seems that gitlab-ci-local does not mount the build directory to service containers, which leads to the issue described in [this older gitlab issue](https://gitlab.com/gitlab-org/gitlab-foss/-/issues/41227).

**Describe the solution you'd like**
Mount the same build volume that is generated for each job (`gcl-job_name-xxxxxx-build`) in all service containers

**Describe alternatives you've considered**
Might be able to use the `--volume` argument to mount something in `.gitlab-ci-local/builds` to be shared by both job and service containers?

**Additional context**
Example of the browser_performance job failing:
```yaml
---
include:
  - template: Verify/Browser-Performance.gitlab-ci.yml

browser_performance:
  variables:
    URL: https://example.com
```

**Comment by haydenseitz** [comment] 2022-10-12 01:18
Sorry for two issues in same day 😅

**Comment by bcouetil** [comment] 2022-10-12 08:57
Hello 😊

Very interesting, since you have created this issue, it means that it works that way. I've never heard of that.

On the documentation you provide, it says at step 6 : `Checkout code in: /builds/group-name/project-name/`

But it does not say that it is on both containers.

Is it the right piece of documentation ?

**Comment by firecow** [comment] 2022-10-12 10:32
We should be able to implement this...

**Comment by haydenseitz** [comment] 2022-10-12 13:56
I don't have private DIND Gitlab runners, so I haven't confirmed myself that the build didn't rectory is shared. But at the bottom of [this section](https://docs.gitlab.com/ee/ci/services/#how-the-health-check-of-services-works) is reads:

> The service container is not providing any networking service, but it’s doing something with the job’s directory (**all services have the job directory mounted as a volume under /builds**). In that case, the service does its job, and because the job is not trying to connect to it, it does not fail.

**Comment by haydenseitz** [comment] 2022-10-12 18:46
Just to double check, I created a test repo to verify.

Here is the job with gitlab-ci-local:
```terminal
$ gitlab-ci-local 
parsing and downloads finished in 42 ms
dind_service starting docker:stable (test)
dind_service started service image: docker:stable-dind with aliases: docker in 1.24 s
dind_service service image: docker:stable-dind healthcheck passed in 2.32 s
dind_service copied to container in 140 ms
dind_service $ printenv CI_PROJECT_DIR
dind_service > /gcl-builds
dind_service $ pwd
dind_service > /gcl-builds
dind_service $ touch newfile
dind_service $ echo "Project files and 'newfile' on the job container:"
dind_service > Project files and 'newfile' on the job container:
dind_service $ ls -a
dind_service > .
dind_service > ..
dind_service > .git
dind_service > README.md
dind_service > newfile
dind_service $ echo "Project files and 'newfile' on the service container:"
dind_service > Project files and 'newfile' on the service container:
dind_service $ docker run --rm -v $(pwd):/work --workdir /work alpine ls -a
dind_service > Unable to find image 'alpine:latest' locally
dind_service > latest: Pulling from library/alpine
dind_service > 213ec9aee27d: Pulling fs layer
dind_service > 213ec9aee27d: Verifying Checksum
dind_service > 213ec9aee27d: Download complete
dind_service > 213ec9aee27d: Pull complete
dind_service > Digest: sha256:bc41182d7ef5ffc53a40b044e725193bc10142a1243f395ee852a8d9730fc2ad
dind_service > Status: Downloaded newer image for alpine:latest
dind_service > .
dind_service > ..
dind_service finished in 11 s

 PASS  dind_service
pipeline finished in 11 s
```

And here is the gitlab pipeline: https://gitlab.com/hseitz/dind-service-example/-/jobs/3164209642

**Comment by firecow** [comment] 2022-10-14 17:15
![image](https://user-images.githubusercontent.com/973602/195903578-ff029872-3609-4e31-b43e-563faa493d62.png)

![image](https://user-images.githubusercontent.com/973602/195903287-149cda38-698c-4456-9b57-a2dfa8486fcb.png)

```yml
# .gitlab-ci.yml
---
shell-build-job:
  tags: [shared-shell-executor]
  script:
    - |
      docker build -t firecow/debug-issue616:ci-${CI_PIPELINE_IID} -f - . <<EOF
      FROM alpine
      CMD cat README.md | tee test.txt
      EOF
    - docker push firecow/debug-issue616:ci-${CI_PIPELINE_IID}

image-debug-job:
  tags: [shared-docker-executor]
  needs: [shell-build-job]
  image: alpine
  services:
    - name: firecow/debug-issue616:ci-${CI_PIPELINE_IID}
  script:
    - pwd
    - ls -all
```

The build folder is not copied/mounted into service container, when I try to reproduce.
Feel free to a full example illustrating the behavior described in the issue and reopen issue :smile:

**Comment by haydenseitz** [comment] 2022-10-14 17:30
Interesting, I'm curious if the build dir is mounted into the service container, but it is not the work dir of the service container. I wonder what `pwd` would show in your service container Dockerfile. That might explain why `cat README.md` fails, if it's not in the current directory, but would be in `/builds/<user>/<project>`. I'll see if I can recreate based off your example.

**Comment by firecow** [comment] 2022-10-14 19:38
Uh, you're right... I'll have to investigate that case as well, on it...

**Comment by firecow** [comment] 2022-10-14 19:54
Using this as `CMD` in service container
```
ls -all /data/gitlab-runner/builds/mjn/gitlab-ci-debugging
```
And there the `README.md` was :smile: 


Using this as `CMD` in service container
```
pwd && echo $CI_PROJECT_DIR
```

pwd came out as `/`
`CI_PROJECT_DIR` was equals to `/data/gitlab-runner/builds/rwzvK8xd/0/mjn/gitlab-ci-debugging`

**Comment by haydenseitz** [comment] 2022-10-14 22:50
I was having difficulty getting a decent example of where the project dir is mounted in each container, so I'm not sure how Gitlab is doing it.

It seems that having both the job container and service container sharing a mount of the project directory is the only way to mount files from the project directory into a third container. [This comment ](https://gitlab.com/gitlab-org/gitlab-foss/-/issues/41227#note_52029664) from the gitlab issue I originally referenced explains that when using DIND and attempting to use a bind mount, you're actually mounting that directory from the dind container (service), not from the container where the docker cmd was ran (job). If you check the source of gitlab's `browser_performance` job I posted above, the job starts a docker container which mounts `pwd`. The reason it must be shared is that earlier in the job, a file is downloaded that is then used in the new container. 

You can see in [this pipeline](https://gitlab.com/gitlab-org/gitlab-foss/-/issues/41227#note_52029664) that files modified in the job container are also reflected in the service container in a Gitlab pipeline.

**Comment by firecow** [comment] 2022-10-15 05:54
DIND is pretty special and require precise runner configuration.

Is this issue, in fact, only about getting DIND to work probably? 
If so please have a look here https://github.com/firecow/gitlab-ci-local/blob/master/examples/docker-in-docker-build/.gitlab-ci-local-env

**Comment by haydenseitz** [comment] 2022-10-15 19:48
My understanding is that Gitlab shared runners use DIND by default. I have DIND working locally with gitlab-ci-local, but the issue is that files are not mounting properly from the job container to the service container. Again, if you check either the browser_performance job or the example I initially posted, you can see that files modified in the job container are also modified when mounting into the service container.

**Comment by firecow** [comment] 2022-10-16 06:26
Right forgot about that sample.
I'll add that exact "test" and implement a shared build folder volume.

**Comment by firecow** [comment] 2022-10-18 17:25
https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Verify/Browser-Performance.gitlab-ci.yml
Where is this template include do you see the service container needing files from the job container or visa versa?

**Comment by firecow** [comment] 2022-11-05 17:14
I'm closing this, until an actual use-case is presented for services and containers sharing filesystem.

**Comment by ticapix** [comment] 2022-11-08 12:34
Hi, 

I do run in this issue with gitlab-ci-local when using a docker image to build docs.

My `.gitlab-ci.yml` is there https://gitlab.com/gaia-x/toolset/gaia-x-document-template/-/blob/main/.gitlab-ci.yml

With gitlab-ci-local, I'm getting:

```shell
debian@work:~/workspace/gaia-x/gaia-x-document-template$ gitlab-ci-local test:html
parsing and downloads finished in 116 ms
test:html starting docker:stable (test)
test:html started service image: docker:dind with aliases: docker in 538 ms
test:html service image: docker:dind healthcheck passed in 3.92 s
test:html copied to container in 220 ms
test:html imported artifacts in 1.92 s
test:html $ docker load -i image/gaia-x_spec_builder.tar
test:html > still running...
test:html > Loaded image: gaia-x_spec_builder:45ad7de
test:html > Loaded image: gaia-x_spec_builder:latest
test:html $ env | grep CI_ > env.txt
test:html $ echo ${CI_PROJECT_DIR}
test:html > /gcl-builds
test:html $ ls ${CI_PROJECT_DIR}/
test:html > Dockerfile
test:html > README.md
test:html > convert_mermaid_graphs.sh
test:html > create_TOC.sh
test:html > docs
test:html > env.txt
test:html > gitlab-ci-template.yml
test:html > image
test:html > mkdocs.yml.j2
test:html > mkdocs_base.yml.j2
test:html > old-gitlab-ci.yml
test:html > puppeteer-config.json
test:html > requirements.txt
test:html > template_html
test:html > template_pdf
test:html $ docker run --name gaia-x_spec_builder --volume ${CI_PROJECT_DIR}/:/data/ --env-file env.txt --interactive --tty -d gaia-x_spec_builder
test:html > 3a7066c42e04e17d14e04ff0f196ba1183d7b7fdd8af30a7203b96d20f7b83da
test:html $ docker exec gaia-x_spec_builder ls -lh /data/
test:html > total 0
test:html $ docker exec gaia-x_spec_builder j2 mkdocs.yml.j2 -o mkdocs.yml
test:html > Traceback (most recent call last):
test:html >   File "/usr/lib/python3.10/site-packages/j2cli/cli.py", line 28, in get_source
test:html >     with io.open(template, 'rt', encoding=self.encoding) as f:
test:html > FileNotFoundError: [Errno 2] No such file or directory: 'mkdocs.yml.j2'
test:html > During handling of the above exception, another exception occurred:
test:html > Traceback (most recent call last):
test:html >   File "/usr/bin/j2", line 8, in <module>
test:html >     sys.exit(main())
test:html >   File "/usr/lib/python3.10/site-packages/j2cli/cli.py", line 202, in main
test:html >     output = render_command(
test:html >   File "/usr/lib/python3.10/site-packages/j2cli/cli.py", line 186, in render_command
test:html >     result = renderer.render(args.template, context)
test:html >   File "/usr/lib/python3.10/site-packages/j2cli/cli.py", line 86, in render
test:html >     .get_template(template_path) \
test:html >   File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
test:html >     return self._load_template(name, globals)
test:html >   File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
test:html >     template = self.loader.load(self, name, self.make_globals(globals))
test:html >   File "/usr/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
test:html >     source, filename, uptodate = self.get_source(environment, name)
test:html >   File "/usr/lib/python3.10/site-packages/j2cli/cli.py", line 31, in get_source
test:html >     raise jinja2.TemplateNotFound(template)
test:html > jinja2.exceptions.TemplateNotFound: mkdocs.yml.j2
test:html finished in 23 s  FAIL 1
```

With Gitlab CI (saas), it's working and I have this log https://gitlab.com/gaia-x/toolset/gaia-x-document-template/-/jobs/3289800866

**Comment by firecow** [comment] 2022-11-08 12:46
Is the mkdocs.yml.j2 file that the containerized j2 is complaining about coming from the docker:dind ?

**Comment by ticapix** [comment] 2022-11-08 12:49
the mkdocs.yml.j2 is a file from the repo. (In the same repo and folder I have the .gitlab-ci.yml file)

**Comment by firecow** [comment] 2022-11-08 14:46
@ticapix I don't think your issue is related to services and containers sharing filesystems.
I'll have a look at your example tonight, and try to figure out, what is going on.

**Comment by maciejmatuszak** [comment] 2022-11-11 05:39
I got the same problem, thanks @ticapix for creating the repo, it helped to narrow the problems. 
This is my understanding
 - per run/job a docker volume is created (not a bonded folder) and mounted under `/gcl-builds` this becomes `CI_PROJECT_DIR`
 - all git files are synchronised to that volume
 - when running dind and attempting to use the `/gcl-builds` as bind source path: `--volume /gcl-builds:/data` it will fail quietly or at least will not do what most of us would expected. other folders will works. ie. `--volume /usr:/usr_data` will correctly mount the `/usr` folder in child container instance

I can not find docker documentation that would spell this out but stackoverflow has multiple example of this problem.

The workaround proposed by @ticapix will solve immediate problem but I suspect the caching and artefact related functionality will be affected.
I think the solution may be to use temporary folder as source of `/gcl-builds` instead of docker volume. This would also help with accessibility to logs and other temporary files generated during pipeline execution. After all the main purpose of running the jobs locally is debugging and quick iteration...

**Comment by firecow** [comment] 2022-11-11 07:33
`/gcl-builds` is not mounted. 

Files are `docker cp` into `<container_id>:/gcl-builds`

```
CI_PROJECT_DIR is equals `/gcl-builds` # in gitlab-ci-local
CI_PROJECT_DIR is equals `/data` # on gitlab-runners
```

If we change CI_PROJECT_DIR to /data in gitlab-ci-local, I think the issue is fixed.

**Comment by firecow** [comment] 2022-11-11 07:50
I think, I got a hold of the issue now.

Service containers needs to have files in the same location in order for docker run commands to actually volume mount from the daemon.

**Comment by firecow** [comment] 2022-11-11 07:53
> Hi, I created initial implementation of running the job in folder instead of docker volume. https://github.com/firecow/gitlab-ci-local/compare/master...maciejmatuszak:gitlab-ci-local:dind-job-in-folder?expand=1
> 
> It is my understanding that running it in bound volume may have performance implications so I made it optional. maybe we could re-open this issue. Will continue on the patch next week

Where did you read that docker volumes have performance impacts? And why do you call them bound volumes ?

**Comment by firecow** [comment] 2022-11-11 08:02
https://github.com/firecow/gitlab-ci-local/pull/661
Check this branch out, I'll add a integration test in the meanwhile.

**Comment by firecow** [comment] 2022-11-11 08:11
There is an integration test in #661 now. I've renamed the issue to `source files missing from service container`

**Closed** 2022-11-11 11:02 UTC
Labels: bug

**Comment by maciejmatuszak** [comment] 2022-11-17 00:43
> Where did you read that docker volumes have performance impacts? And why do you call them bound volumes ?
>
> I would call those two that you made optional, regular named docker volumes.

The Performance hit was mainly personal experience, but googling the issue it seems to be Macos specific.
`bound volumes` I should say `bound directories` as opposed to docker volumes
@firecow, after #661 it is still not quite there, despite the new unit test passing it still not works in the example when you add `docker run ..` and try to access the files from the new container it will not work. I spend 2 days on it and I think I have better understanding. 
I inspected the containers and volumes created originally by gitlab-runner. The dind container has `/builds` and `/var/lib/docker` 
 mounted as docker volumes, I do not understand it completely but it looks like it is critical for sharing the filed between various docker containers in dind arrangement.
```json
[
    {
...
...
        "Name": "/runner-yxo2pgts-project-34594612-concurrent-0-70f8f233861b092c-docker-0",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
...
...
        "HostConfig": {
            "Binds": [
                "runner-yxo2pgts-project-34594612-concurrent-0-cache-904f6ed42e0fa2b14c1d7a2ed6f1875e:/certs/client",
                "runner-yxo2pgts-project-34594612-concurrent-0-cache-3c3f060a0374fc8bc39395164f415a70:/cache",
                "runner-yxo2pgts-project-34594612-concurrent-0-70f8f233861b092c-cache-c33bcaa1fd2c77edfc3893b41966cea8:/builds"
            ],
...
...
        "Mounts": [
            {
                "Type": "volume",
                "Name": "runner-yxo2pgts-project-34594612-concurrent-0-cache-904f6ed42e0fa2b14c1d7a2ed6f1875e",
                "Source": "/var/lib/docker/volumes/runner-yxo2pgts-project-34594612-concurrent-0-cache-904f6ed42e0fa2b14c1d7a2ed6f1875e/_data",
                "Destination": "/certs/client",
                "Driver": "local",
                "Mode": "z",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "volume",
                "Name": "runner-yxo2pgts-project-34594612-concurrent-0-cache-3c3f060a0374fc8bc39395164f415a70",
                "Source": "/var/lib/docker/volumes/runner-yxo2pgts-project-34594612-concurrent-0-cache-3c3f060a0374fc8bc39395164f415a70/_data",
                "Destination": "/cache",
                "Driver": "local",
                "Mode": "z",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "volume",
                "Name": "runner-yxo2pgts-project-34594612-concurrent-0-70f8f233861b092c-cache-c33bcaa1fd2c77edfc3893b41966cea8",
                "Source": "/var/lib/docker/volumes/runner-yxo2pgts-project-34594612-concurrent-0-70f8f233861b092c-cache-c33bcaa1fd2c77edfc3893b41966cea8/_data",
                "Destination": "/builds",
                "Driver": "local",
                "Mode": "z",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "volume",
                "Name": "a7dfa774b0264c9c8ed1722899900ec3bd82b0f8db5b6c31e786be90eb227ce9",
                "Source": "/var/lib/docker/volumes/a7dfa774b0264c9c8ed1722899900ec3bd82b0f8db5b6c31e786be90eb227ce9/_data",
                "Destination": "/var/lib/docker",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
    }
]
```

I think this is the path forward:
- the `/builds` volume has to be created and populated before services or job is started
- the `/builds` volume has to be mounted to services and job containers. This will mean that that services, jobs, containers spun in job will all operate on the same files not its own copy
- dind is special service and requires volume `/var/lib/docker` we need to be able to detect or designate service as dind.
- the path `/builds/group/project` is mentioned in documentation I think we should preserve this path instead of `/gcl-builds` to minimise impact on existing pipelines
- not related but the `.git` folder has to be preserved, it prevents gunning of git commands in job

I have 'prove of concept' code in https://github.com/firecow/gitlab-ci-local/compare/master...maciejmatuszak:gitlab-ci-local:dind_volume_sharing?expand=1

**Comment by firecow** [comment] 2022-11-17 05:19
https://github.com/firecow/gitlab-ci-local/pull/665

This PR will fix . I think 😁
