### ISSUE TITLE
Jobs in generated piplines not executed

### ISSUE THREAD

**Issue by alexey-vostrikov** [firecow/gitlab-ci-local#1305] opened 2024-07-26 15:44 UTC
**Minimal .gitlab-ci.yml illustrating the issue**

clone https://gitlab.com/gitlab-org/project-templates/jsonnet

run gitlab-ci-local

**Expected behavior**

jobs in triggered pipeline should run

job/blue, job/cats, job/foxes, job/goats, job/green, job/red

**Host information**
Ubuntu 24.10
gitlabci-local 4.52.2

**Containerd binary**
docker

**Comment by firecow** [comment] 2024-08-01 08:45
I believe this is a duplicate of https://github.com/firecow/gitlab-ci-local/issues/94

**Closed by firecow** 2024-08-01 08:45 UTC
Labels: duplicate
