### ISSUE TITLE
Run downstream pipeline jobs

### ISSUE THREAD

**Issue by Time0o** [firecow/gitlab-ci-local#879] opened 2023-05-26 07:24 UTC
This is in response to Issue  #876. The problem was/is that the job I tried to run actually triggers a downstream pipeline. `gitlab-ci-local` does not run the jobs contained in that downstream pipeline. Is this a known limitation? Is there another way I can run downstream pipeline jobs? Here is a minimal example: https://github.com/Time0o/gitlab-ci-local-test.

`gitlab-ci-local downstream-pipeline` outputs:

```
parsing and downloads finished in 31 ms
downstream-pipeline starting shell (test)
downstream-pipeline finished in 4.99 ms

 PASS  downstream-pipeline
```

And `gitlab-ci-local test-job` yields:

```
parsing and downloads finished in 30 ms
test-job could not be found
```

**Comment by firecow** [comment] 2023-05-26 08:15
It looks like a duplicate of this issue https://github.com/firecow/gitlab-ci-local/issues/94

**Closed** 2023-05-26 08:16 UTC
