### ISSUE TITLE
Running as root is not recommended

### ISSUE THREAD

**Issue by dannywillems** [firecow/gitlab-ci-local#701] opened 2022-12-19 14:26 UTC
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
stages:
  - test-alpine

build-ocaml-4.08-alpine-3.14:
  image: ocaml/opam:alpine-3.14-ocaml-4.08
  stage: test-alpine
  script:
    - echo "hello"
```

**Expected behavior**

See https://gitlab.com/dannywillems/gitlab-ci-local-test-discrepancy/-/jobs/3496300546

**Host information**
Ubuntu
gitlab-ci-local 4.1.33

**Additional context**

The error
```
  > [WARNING] Running as root is not recommended
  > [ERROR] Opam has not been initialised, please run `opam init'
```
comes from the docker image, and it is from `opam`, the OCaml Package Manager. However, it should not make the job fail.

**Comment by firecow** [comment] 2022-12-19 15:00
https://github.com/firecow/gitlab-ci-local/issues/671
I have a feeling this is related to this feature request.

**Comment by dannywillems** [comment] 2022-12-19 15:51
> Is "running as root" being disabled on the runner in your "expected behavior" example somehow?

I don't know how I could verify this. Installing `gitlab-runner` using https://docs.gitlab.com/runner/install/ and running `gitlab-runner exec docker [job]` works well.

**Comment by dannywillems** [comment] 2022-12-19 15:52
The user should not be `root`, but `opam`:
```
$ docker run -it ocaml/opam:alpine-3.14-ocaml-4.08
# in the container
$ whoami
> opam
```

**Comment by firecow** [comment] 2022-12-19 15:58
That depends on the runner or gitlab instance.

Who have setup the runner used in your "expected behavior" link?

**Comment by dannywillems** [comment] 2022-12-19 16:09
> Who have setup the runner used in your "expected behavior" link?
The runner used in my "expected behavior" is the one from Gitlab: 1-blue.shared.runners-manager.gitlab.com/default, which can be reproduced by using `gitlab-runner` you can download on your machine using the link given above.

**Comment by dannywillems** [comment] 2022-12-19 16:10
> Is the FF_DISABLE_UMASK_FOR_DOCKER_EXECUTOR flag enabled?

See https://docs.gitlab.com/runner/configuration/feature-flags.html I suppose

**Comment by firecow** [comment] 2022-12-19 16:19
gitlab-runner 15.6.0~beta.186.ga889181a

Looks like gitlab is moving towards "no-root" docker-executors or something similar.

We already have an issue addressing this.

I'm closing this as dublicate.

**Closed** 2022-12-19 16:19 UTC
Labels: duplicate, elaborate
