### ISSUE TITLE
Unable to pass CI_JOB_TOKEN, CI_REGISTRY via gitlab-ci-local variables (regression since 4.26)

### ISSUE THREAD

**Issue by Rush** [firecow/gitlab-ci-local#408] opened 2022-03-16 20:37 UTC
Last known working version is 4.25.1 and thus workwround is to do:
```
npm install -g gitlab-ci-local@~4.25
```

**Minimal .gitlab-ci.yml illustrating the issue**

Set in `.gitlab-ci-local-env`
```
---
CI_JOB_TOKEN: SOME_TOKEN
CI_REGISTRY: registry.gitlab.com
```

```yml
---
job:
  script:
    - echo "CI $CI_JOB_TOKEN $CI_REGISTRY"
```

**Expected behavior**

```
Output of:
CI SOME_TOKEN registry.gitlab.com
```

**Host information**
Ubuntu
gitlab-ci-local 4.2.9.0

**Additional context**
My CI pipeline is referencing images from my Gitlab registry. I need full access to the registry.

**Comment by firecow** [comment] 2022-03-17 18:28
I cannot reproduce your example.

```
mjn@mjn-laptop:~$ gitlab-ci-local --version
4.25.1
mjn@mjn-laptop:~$ gitlab-ci-local 
parsing and downloads finished in 59 ms
job starting shell (test)
job $ echo "CI $CI_JOB_TOKEN $CI_REGISTRY"
job > CI  registry.gitlab.com
job finished in 29 ms

 PASS  job
pipeline finished in 139 ms
mjn@mjn-laptop:~$ cat .gitlab-ci-local-env 
---
CI_JOB_TOKEN: SOME_TOKEN
CI_REGISTRY: registry.gitlab.com
```

Also in "Additional context" you've put 4.1.33. 
I don't recall ever having published such version :smile: And neither can npmjs.com
```
mjn@mjn-laptop:~$ sudo npm install -g gitlab-ci-local@4.1.33
npm ERR! code ETARGET
npm ERR! notarget No matching version found for gitlab-ci-local@4.1.33.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-03-17T18_26_19_741Z-debug-0.log
```

**Comment by Rush** [comment] 2022-03-17 18:51
Thanks for the reply. Sorry for the confusion with the version. I meant 4.29.0 as the latest that's broken 4.25.1 being the last working version. 

Using the syntax you proposed everything works:
```
VARIABLE="CI_JOB_TOKEN=SOME_TOKEN CI_REGISTRY=registry.gitlab.com"
```
but using normal yaml syntax does not
```
---
CI_JOB_TOKEN: 1nS4GE1wyCZGXbw5BJq5
CI_REGISTRY: registry.gitlab.com
```

The latter syntax works with 4.25.1 though.

**Comment by firecow** [comment] 2022-03-17 18:58
You must be confusing .gitlab-ci-local-env with ~/.gitlab-ci-local/variables.yml

**Comment by Rush** [comment] 2022-03-17 19:11
Hm perhaps. Maybe Just assumed they're the same format? Anyhow I started looking at `.gitlab-ci-local-env` as the variables in `~/.gitlab-ci-local/variables.yml` stopped working:

```
---
project:
  gitlab.com/mygroup/myproject
    CI_JOB_TOKEN: SOME_TOKEN
    CI_REGISTRY: registry.gitlab.com
```

Does not work from 4.26.x onward.

**Comment by firecow** [comment] 2022-03-17 20:10
Ah, ok... Now the issue makes sense 🤣
I'll try to reproduce, when i get home...

**Comment by firecow** [comment] 2022-03-18 09:24
```yml
---
project:
  gitlab.com/mygroup/myproject
    CI_JOB_TOKEN: SOME_TOKEN
    CI_REGISTRY: registry.gitlab.com
```
This is not valid YML @Rush

**Comment by firecow** [comment] 2022-03-18 09:30
```shell
mjn@mjn-laptop:~$ gitlab-ci-local --version
4.29.0

mjn@mjn-laptop:~$ gitlab-ci-local 
parsing and downloads finished in 16 ms
job starting shell (test)
job $ echo "CI $CI_JOB_TOKEN $CI_REGISTRY"
job > CI SOME_TOKEN registry.gitlab.com
job finished in 12 ms

 PASS  job
pipeline finished in 62 ms

mjn@mjn-laptop:~$ gitlab-ci-local --version
4.29.0

mjn@mjn-laptop:~$ cat ~/.gitlab-ci-local/variables.yml 
---
project:
  gitlab.com/firecow/example:
    CI_JOB_TOKEN: SOME_TOKEN
    CI_REGISTRY: registry.gitlab.com
```

Home variables works as expected. 

I'm closing this issue.
Feel free to reopen, if you are able to reproduce via a minimal example on your machine.

**Closed by firecow** 2022-03-18 09:30 UTC
Labels: elaborate
