### ISSUE TITLE
Limit on number of jobs?

### ISSUE THREAD

**Issue by gilzow** [firecow/gitlab-ci-local#142] opened 2021-04-20 20:11 UTC
I've been using the dynamic pipeline feature you added in #57 but am hitting another snag. 

Testing a WordPress multisite. My main pipeline dynamically generates a new gitlab-ci.yml file for to run visual regression testing against each site in the multisite, one job per site. This specific WordPress site has 27 sites, so 27 jobs were created. When I ran gitlab-c-local against the generated gitlabci.yml file, it errored out with 
`must specify at least one container source`
I then removed all the jobs except one, tried again and it the whole pipeline ran successfully. I then added jobs one by one and discovered that after 9 jobs, I receive the error message again. It doesn't matter _which_ jobs I have, it fails with anything more than 9 jobs. 

Is the 9 jobs a known limitation?

**Comment by bcouetil** [comment] 2021-04-20 20:21
Duplicate of #130 which is closed.

Try release 4.16.0 and tell us if still failing 😉

**Comment by firecow** [comment] 2021-04-20 20:23
@bcouetil You fast man 😂

**Comment by bcouetil** [comment] 2021-04-20 20:25
I'm already on the motorcycle 😎

**Comment by gilzow** [comment] 2021-04-20 20:54
apologies, I searched the issues looking for "job limits" and didnt think to look for the specific error message.

I was on 4.13.0 and just updated to 4.16.0. Seems to be working now. Sorry about that.

**Comment by firecow** [comment] 2021-04-21 04:20
@gilzow It is totally fine. We are just happy that you are using the tool

**Closed by firecow** 2021-04-21 04:20 UTC
Labels: duplicate
