### ISSUE TITLE
Can not checkout this repo in gitbash

### ISSUE THREAD

**Issue by ahoehma** [firecow/gitlab-ci-local#1412] opened 2024-11-05 07:53 UTC
I try to clone the repo but got a checkout error. Hmm..

```
$git clone https://github.com/firecow/gitlab-ci-local.git
Cloning into 'gitlab-ci-local'...
remote: Enumerating objects: 13225, done.
remote: Counting objects: 100% (3377/3377), done.
remote: Compressing objects: 100% (561/561), done.
remote: Total 13225 (delta 3109), reused 2914 (delta 2809), pack-reused 9848 (from 1)
Receiving objects: 100% (13225/13225), 382.63 MiB | 15.45 MiB/s, done.
Resolving deltas: 100% (8505/8505), done.
error: invalid path 'tests/test-cases/rules-changes/.gitlab-ci-rules:changes:paths.yml'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

$git -v
git version 2.47.0.windows.2

**Comment by ANGkeith** [comment] 2024-11-05 08:52
argh..  not sure but maybe path issue here? 

`error: invalid path 'tests/test-cases/rules-changes/.gitlab-ci-rules:changes:paths.yml'`


don't really have a windows machine to investigate ..

**Comment by ahoehma** [comment] 2024-11-05 09:16
I never had such an error before :-) But I can start googling little bit.

**Comment by ANGkeith** [comment] 2024-11-05 13:51
duplicate of #1279

**Closed by ANGkeith** 2024-11-05 13:51 UTC
